#ifndef __CAPWAP_DFA_HEADER__
#define __CAPWAP_DFA_HEADER__

#define CAPWAP_UNDEF_STATE								-1
#define CAPWAP_START_STATE								0
#define CAPWAP_START_TO_IDLE_STATE						1
#define CAPWAP_IDLE_STATE								2
#define CAPWAP_IDLE_TO_DISCOVERY_STATE					3
#define CAPWAP_IDLE_TO_DTLS_SETUP_STATE					4
#define CAPWAP_DISCOVERY_STATE							5
#define CAPWAP_DISCOVERY_TO_IDLE_STATE					6
#define CAPWAP_DISCOVERY_TO_SULKING_STATE				7
#define CAPWAP_DISCOVERY_TO_DTLS_SETUP_STATE			8
#define CAPWAP_SULKING_STATE							9
#define CAPWAP_SULKING_TO_IDLE_STATE					10
#define CAPWAP_DTLS_SETUP_STATE							11
#define CAPWAP_DTLS_SETUP_TO_IDLE_STATE					12
#define CAPWAP_DTLS_SETUP_TO_SULKING_STATE				13
#define CAPWAP_DTLS_SETUP_TO_AUTHORIZE_STATE			14
#define CAPWAP_AUTHORIZE_STATE							15
#define CAPWAP_AUTHORIZE_TO_DTLS_SETUP_STATE			16
#define CAPWAP_AUTHORIZE_TO_DTLS_CONNECT_STATE			17
#define CAPWAP_AUTHORIZE_TO_DTLS_TEARDOWN_STATE			18
#define CAPWAP_DTLS_CONNECT_STATE						19
#define CAPWAP_DTLS_CONNECT_TO_DTLS_TEARDOWN_STATE		20
#define CAPWAP_DTLS_CONNECT_TO_JOIN_STATE				21
#define CAPWAP_DTLS_TEARDOWN_STATE						22
#define CAPWAP_DTLS_TEARDOWN_TO_IDLE_STATE				23
#define CAPWAP_DTLS_TEARDOWN_TO_SULKING_STATE			24
#define CAPWAP_DTLS_TEARDOWN_TO_DEAD_STATE				25
#define CAPWAP_JOIN_STATE								26
#define CAPWAP_POSTJOIN_STATE							27
#define CAPWAP_JOIN_TO_DTLS_TEARDOWN_STATE				28
#define CAPWAP_JOIN_TO_IMAGE_DATA_STATE					29
#define CAPWAP_JOIN_TO_CONFIGURE_STATE					30
#define CAPWAP_IMAGE_DATA_STATE							31
#define CAPWAP_IMAGE_DATA_TO_RESET_STATE				32
#define CAPWAP_IMAGE_DATA_TO_DTLS_TEARDOWN_STATE		33
#define CAPWAP_CONFIGURE_STATE							34
#define CAPWAP_CONFIGURE_TO_RESET_STATE					35
#define CAPWAP_CONFIGURE_TO_DTLS_TEARDOWN_STATE			36
#define CAPWAP_CONFIGURE_TO_DATA_CHECK_STATE			37
#define CAPWAP_RESET_STATE								38
#define CAPWAP_RESET_TO_DTLS_TEARDOWN_STATE				39
#define CAPWAP_DATA_CHECK_STATE							40
#define CAPWAP_DATA_CHECK_TO_DTLS_TEARDOWN_STATE		41
#define CAPWAP_DATA_CHECK_TO_RUN_STATE					42
#define CAPWAP_RUN_STATE								43
#define CAPWAP_RUN_TO_DTLS_TEARDOWN_STATE				44
#define CAPWAP_RUN_TO_RESET_STATE						45
#define CAPWAP_DEAD_STATE								46
#define CAPWAP_LAST_STATE								46

/* */
char* capwap_dfa_getname(int state);

#endif /* __CAPWAP_DFA_HEADER__ */
