#ifndef __CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_HEADER__
#define __CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_HEADER__

#define CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_PROFILE_VENDOR		0
#define CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_PROFILE_TYPE		1038
#define CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_PROFILE			(struct capwap_message_element_id){ .vendor = CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_PROFILE_VENDOR, .type = CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_PROFILE_TYPE }


#define CAPWAP_STATION_SESSION_KEY_PAIRWISE_TSC_LENGTH			6
#define CAPWAP_STATION_SESSION_KEY_PAIRWISE_RSC_LENGTH			6

#define CAPWAP_STATION_SESSION_KEY_AKM_ONLY					0x8000
#define CAPWAP_STATION_SESSION_KEY_AC_ENCRYPT				0x4000

struct capwap_80211_stationkey_element {
	uint8_t address[MACADDRESS_EUI48_LENGTH];
	uint16_t flags;
	uint8_t pairwisetsc[CAPWAP_STATION_SESSION_KEY_PAIRWISE_TSC_LENGTH];
	uint8_t pairwisersc[CAPWAP_STATION_SESSION_KEY_PAIRWISE_RSC_LENGTH];
	uint16_t keylength;
	uint8_t* key;
};

extern const struct capwap_message_elements_ops capwap_element_80211_stationkey_ops;

#endif /* __CAPWAP_ELEMENT_80211_STATION_SESSION_KEY_HEADER__ */
