#ifndef __CAPWAP_ELEMENT_80211_UPDATE_WLAN_HEADER__
#define __CAPWAP_ELEMENT_80211_UPDATE_WLAN_HEADER__

#define CAPWAP_ELEMENT_80211_UPDATE_WLAN				1044

#define CAPWAP_UPDATE_WLAN_CAPABILITY_ESS				0x8000
#define CAPWAP_UPDATE_WLAN_CAPABILITY_IBSS				0x4000
#define CAPWAP_UPDATE_WLAN_CAPABILITY_CFPOLLABLE		0x2000
#define CAPWAP_UPDATE_WLAN_CAPABILITY_CFPOLLREQUEST		0x1000
#define CAPWAP_UPDATE_WLAN_CAPABILITY_PRIVACY			0x0800
#define CAPWAP_UPDATE_WLAN_CAPABILITY_SHORTPREAMBLE		0x0400
#define CAPWAP_UPDATE_WLAN_CAPABILITY_PBCC				0x0200
#define CAPWAP_UPDATE_WLAN_CAPABILITY_CHANNELAGILITY	0x0100
#define CAPWAP_UPDATE_WLAN_CAPABILITY_SPECTRUMMAN		0x0080
#define CAPWAP_UPDATE_WLAN_CAPABILITY_QOS				0x0040
#define CAPWAP_UPDATE_WLAN_CAPABILITY_SHORTSLOTTIME		0x0020
#define CAPWAP_UPDATE_WLAN_CAPABILITY_APSD				0x0010
#define CAPWAP_UPDATE_WLAN_CAPABILITY_DSSS_OFDM			0x0004
#define CAPWAP_UPDATE_WLAN_CAPABILITY_DELAYEDACK		0x0002
#define CAPWAP_UPDATE_WLAN_CAPABILITY_IMMEDIATEACK		0x0001

#define CAPWAP_UPDATE_WLAN_KEY_STATUS_MULTICASTKEY		0
#define CAPWAP_UPDATE_WLAN_KEY_STATUS_WEP				1
#define CAPWAP_UPDATE_WLAN_KEY_STATUS_REKEYINGGTK		2
#define CAPWAP_UPDATE_WLAN_KEY_STATUS_COMPLETEGTK		3

struct capwap_80211_updatewlan_element {
	uint8_t radioid;
	uint8_t wlanid;
	uint16_t capability;
	uint8_t keyindex;
	uint8_t keystatus;
	uint16_t keylength;
	uint8_t* key;
};

extern const struct capwap_message_elements_ops capwap_element_80211_updatewlan_ops;

#endif /* __CAPWAP_ELEMENT_80211_UPDATE_WLAN_HEADER__ */
